
package com.samaspace.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceBank", targetNamespace = "http://service.samaspace.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceBank {


    /**
     * 
     * @param codeAccount
     * @return
     *     returns com.samaspace.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "takeOneAccount", targetNamespace = "http://service.samaspace.com/", className = "com.samaspace.service.TakeOneAccount")
    @ResponseWrapper(localName = "takeOneAccountResponse", targetNamespace = "http://service.samaspace.com/", className = "com.samaspace.service.TakeOneAccountResponse")
    @Action(input = "http://service.samaspace.com/ServiceBank/takeOneAccountRequest", output = "http://service.samaspace.com/ServiceBank/takeOneAccountResponse")
    public Compte takeOneAccount(
        @WebParam(name = "codeAccount", targetNamespace = "")
        Long codeAccount);

    /**
     * 
     * @param amountOfAccount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionDollarToDHS", targetNamespace = "http://service.samaspace.com/", className = "com.samaspace.service.ConversionDollarToDHS")
    @ResponseWrapper(localName = "conversionDollarToDHSResponse", targetNamespace = "http://service.samaspace.com/", className = "com.samaspace.service.ConversionDollarToDHSResponse")
    @Action(input = "http://service.samaspace.com/ServiceBank/conversionDollarToDHSRequest", output = "http://service.samaspace.com/ServiceBank/conversionDollarToDHSResponse")
    public double conversionDollarToDHS(
        @WebParam(name = "amountOfAccount", targetNamespace = "")
        double amountOfAccount);

    /**
     * 
     * @return
     *     returns java.util.List<com.samaspace.service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAccounts", targetNamespace = "http://service.samaspace.com/", className = "com.samaspace.service.GetAllAccounts")
    @ResponseWrapper(localName = "getAllAccountsResponse", targetNamespace = "http://service.samaspace.com/", className = "com.samaspace.service.GetAllAccountsResponse")
    @Action(input = "http://service.samaspace.com/ServiceBank/getAllAccountsRequest", output = "http://service.samaspace.com/ServiceBank/getAllAccountsResponse")
    public List<Compte> getAllAccounts();

}
